import RPi.GPIO as g
from time import sleep
g.setwarnings(False)
g.setmode(g.BOARD)
g.setup(8,g.OUT,initial=g.LOW)
g.setup(10,g.OUT,initial=g.LOW)
g.setup(12,g.OUT,initial=g.LOW)
# while True: //serial
# 	g.output(8,g.HIGH)
# 	sleep(1)
# 	g.output(8,g.LOW)
# 	sleep(1)
# 	g.output(10,g.HIGH)
# 	sleep(1)
# 	g.output(10,g.LOW)
# 	sleep(1)
# 	g.output(12,g.HIGH)
# 	sleep(1)
# 	g.output(12,g.LOW)
# 	sleep(1)
# while True: //reverse
# 	g.output(8,g.HIGH)
# 	sleep(1)
# 	g.output(8,g.LOW)
# 	sleep(1)
# 	g.output(10,g.HIGH)
# 	sleep(1)
# 	g.output(10,g.LOW)
# 	sleep(1)
# 	g.output(12,g.HIGH)
# 	sleep(1)
# 	g.output(12,g.LOW)
# 	sleep(1)
# 	g.output(12,g.HIGH)
# 	sleep(1)
# 	g.output(12,g.LOW)
# 	sleep(1)
# 	g.output(10,g.HIGH)
# 	sleep(1)
# 	g.output(10,g.LOW)
# 	sleep(1)
# 	g.output(8,g.HIGH)
# 	sleep(1)
# 	g.output(8,g.LOW)
# 	sleep(1)
choices=[8,10,12]
while True: #random
	temp=random.choice(choices)
	g.output(temp,g.HIGH)
	sleep(1)
	g.output(temp,g.LOW)
	sleep(1)
